### ISSUE TITLE
Unable to superpose the before and after text

### ISSUE THREAD

**Issue by Benoit1980** [zhenghuahou/text-diff#2]
Hello,

2 very nice features would have been great to have on your library:

1)Have both the red and green changes in the same block(like Grammarly).
2)Instead of having 1 or 2 letters added or removed, have the possibility to have the entire words colored instead as it is very difficult to read when only 1 or 2 letters are highlighted.

Thanks!

**Comment by sebastiansandqvist** [comment]
@Benoit1980 For (2), you can use a space character as the `separator` when using `diffPatchBySeparator`.

**Comment by Benoit1980** [comment]
Thanks sorry I did not see your reply.
